// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: click.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type BulkInsertClicksParams struct {
	LinkID    uuid.UUID
	ClickedAt time.Time
	Referrer  *string
	UserAgent *string
}

const countClicksForLink = `-- name: CountClicksForLink :one
SELECT count(*) FROM clicks WHERE link_id = $1
`

// Used by the integration tests to assert the denormalized links.click_count
// has not drifted from the raw event table.
func (q *Queries) CountClicksForLink(ctx context.Context, linkID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClicksForLink, linkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getClicksPerDay = `-- name: GetClicksPerDay :many
SELECT
    d.day::date                   AS day,
    COALESCE(c.clicks, 0)::bigint AS clicks
FROM generate_series($1::date, $2::date, interval '1 day') AS d (day)
LEFT JOIN (
    SELECT date_trunc('day', clicked_at AT TIME ZONE 'UTC')::date AS day,
           count(*) AS clicks
    FROM clicks
    WHERE link_id = $3
      AND clicked_at >= $4::timestamptz
      AND clicked_at <  $5::timestamptz
    GROUP BY 1
) AS c ON c.day = d.day::date
ORDER BY d.day
`

type GetClicksPerDayParams struct {
	FromDay    time.Time
	ToDay      time.Time
	LinkID     uuid.UUID
	RangeStart time.Time
	RangeEnd   time.Time
}

type GetClicksPerDayRow struct {
	Day    time.Time
	Clicks int64
}

// Zero-filled buckets. Without generate_series a day with no clicks is simply
// absent from the result, and the chart draws a line straight across the gap —
// which reads as "traffic held steady" when the truth is "nobody clicked".
//
// The window is passed as an explicit half-open timestamptz range
// [range_start, range_end) rather than derived from the date bounds in SQL. That
// keeps the predicate sargable, so Postgres range-scans clicks_link_time_idx
// instead of evaluating a date expression for every row in the table.
func (q *Queries) GetClicksPerDay(ctx context.Context, arg GetClicksPerDayParams) ([]GetClicksPerDayRow, error) {
	rows, err := q.db.Query(ctx, getClicksPerDay,
		arg.FromDay,
		arg.ToDay,
		arg.LinkID,
		arg.RangeStart,
		arg.RangeEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClicksPerDayRow{}
	for rows.Next() {
		var i GetClicksPerDayRow
		if err := rows.Scan(&i.Day, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementClickCounts = `-- name: IncrementClickCounts :exec
UPDATE links l
SET click_count = l.click_count + v.n
FROM (
    SELECT unnest($1::uuid[]) AS id,
           unnest($2::bigint[])  AS n
    ORDER BY 1
) AS v
WHERE l.id = v.id
`

type IncrementClickCountsParams struct {
	LinkIds []uuid.UUID
	Counts  []int64
}

// Runs in the same transaction as BulkInsertClicks, so a click row and its
// counter increment commit or roll back together.
//
// Static SQL over two parallel arrays rather than a dynamically built VALUES
// list: one prepared statement, one plan, no string building. Ordering the
// update by id keeps concurrent worker transactions from deadlocking when their
// batches touch the same links in different orders.
func (q *Queries) IncrementClickCounts(ctx context.Context, arg IncrementClickCountsParams) error {
	_, err := q.db.Exec(ctx, incrementClickCounts, arg.LinkIds, arg.Counts)
	return err
}
