// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkInsertClicks implements pgx.CopyFromSource.
type iteratorForBulkInsertClicks struct {
	rows                 []BulkInsertClicksParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertClicks) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertClicks) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].LinkID,
		r.rows[0].ClickedAt,
		r.rows[0].Referrer,
		r.rows[0].UserAgent,
	}, nil
}

func (r iteratorForBulkInsertClicks) Err() error {
	return nil
}

// Compiles to pgx CopyFrom: one COPY stream instead of N round trips. This is
// the entire reason the worker accumulates a batch before writing.
func (q *Queries) BulkInsertClicks(ctx context.Context, arg []BulkInsertClicksParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"clicks"}, []string{"link_id", "clicked_at", "referrer", "user_agent"}, &iteratorForBulkInsertClicks{rows: arg})
}
