// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: link.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (user_id, short_code, long_url, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, short_code, long_url, click_count, created_at, expires_at
`

type CreateLinkParams struct {
	UserID    uuid.UUID
	ShortCode string
	LongUrl   string
	ExpiresAt *time.Time
}

// No SELECT-then-INSERT: we insert and let links_short_code_key reject a
// collision. The repository turns 23505 into ErrAliasTaken, and the service
// retries with a fresh code when the alias was generated rather than chosen.
// expires_at is nullable; NULL means the link never expires.
func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.UserID,
		arg.ShortCode,
		arg.LongUrl,
		arg.ExpiresAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.LongUrl,
		&i.ClickCount,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteLinkByShortCode = `-- name: DeleteLinkByShortCode :one
DELETE FROM links
WHERE short_code = $1 AND user_id = $2
RETURNING short_code
`

type DeleteLinkByShortCodeParams struct {
	ShortCode string
	UserID    uuid.UUID
}

// RETURNING lets the caller tell "deleted" from "was never yours", without a
// prior SELECT. Clicks cascade.
func (q *Queries) DeleteLinkByShortCode(ctx context.Context, arg DeleteLinkByShortCodeParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteLinkByShortCode, arg.ShortCode, arg.UserID)
	var short_code string
	err := row.Scan(&short_code)
	return short_code, err
}

const getLinkByShortCode = `-- name: GetLinkByShortCode :one
SELECT id, user_id, short_code, long_url, click_count, created_at, expires_at FROM links WHERE short_code = $1
`

// The redirect hot path, on cache miss only.
func (q *Queries) GetLinkByShortCode(ctx context.Context, shortCode string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByShortCode, shortCode)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.LongUrl,
		&i.ClickCount,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLinkByShortCodeForUser = `-- name: GetLinkByShortCodeForUser :one
SELECT id, user_id, short_code, long_url, click_count, created_at, expires_at FROM links WHERE short_code = $1 AND user_id = $2
`

type GetLinkByShortCodeForUserParams struct {
	ShortCode string
	UserID    uuid.UUID
}

// Ownership is part of the predicate, not a check after the fact: a link that
// belongs to someone else is indistinguishable from one that does not exist,
// so stats cannot be used to probe for other users' codes.
func (q *Queries) GetLinkByShortCodeForUser(ctx context.Context, arg GetLinkByShortCodeForUserParams) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByShortCodeForUser, arg.ShortCode, arg.UserID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.LongUrl,
		&i.ClickCount,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listLinksAfter = `-- name: ListLinksAfter :many
SELECT id, user_id, short_code, long_url, click_count, created_at, expires_at FROM links
WHERE user_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListLinksAfterParams struct {
	UserID         uuid.UUID
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageSize       int32
}

// Row-value comparison, not `created_at < x OR (created_at = x AND id < y)`.
// Postgres can drive links_user_created_idx directly from a row constructor,
// and it is correct when two links share a created_at to the microsecond.
func (q *Queries) ListLinksAfter(ctx context.Context, arg ListLinksAfterParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinksAfter,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShortCode,
			&i.LongUrl,
			&i.ClickCount,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksFirstPage = `-- name: ListLinksFirstPage :many
SELECT id, user_id, short_code, long_url, click_count, created_at, expires_at FROM links
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListLinksFirstPageParams struct {
	UserID   uuid.UUID
	PageSize int32
}

// Keyset pagination, page one. Separate from ListLinksAfter because sqlc emits
// static SQL: a `WHERE ... OR @cursor IS NULL` predicate would collapse into a
// filter that cannot use links_user_created_idx. Two honest queries beat one
// query that quietly stops using its index.
// Callers pass page_size = limit + 1 and use the extra row to detect "has more".
func (q *Queries) ListLinksFirstPage(ctx context.Context, arg ListLinksFirstPageParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinksFirstPage, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShortCode,
			&i.LongUrl,
			&i.ClickCount,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
