// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Click struct {
	ID        int64
	LinkID    uuid.UUID
	ClickedAt time.Time
	Referrer  *string
	UserAgent *string
}

type Link struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ShortCode  string
	LongUrl    string
	ClickCount int64
	CreatedAt  time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
