// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Compiles to pgx CopyFrom: one COPY stream instead of N round trips. This is
	// the entire reason the worker accumulates a batch before writing.
	BulkInsertClicks(ctx context.Context, arg []BulkInsertClicksParams) (int64, error)
	// Used by the integration tests to assert the denormalized links.click_count
	// has not drifted from the raw event table.
	CountClicksForLink(ctx context.Context, linkID uuid.UUID) (int64, error)
	// No SELECT-then-INSERT: we insert and let links_short_code_key reject a
	// collision. The repository turns 23505 into ErrAliasTaken, and the service
	// retries with a fresh code when the alias was generated rather than chosen.
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	// The UNIQUE index on email is the duplicate check. Racing registrations both
	// reach here; one gets 23505, which the repository maps to ErrEmailTaken.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// RETURNING lets the caller tell "deleted" from "was never yours", without a
	// prior SELECT. Clicks cascade.
	DeleteLinkByShortCode(ctx context.Context, arg DeleteLinkByShortCodeParams) (string, error)
	// Zero-filled buckets. Without generate_series a day with no clicks is simply
	// absent from the result, and the chart draws a line straight across the gap —
	// which reads as "traffic held steady" when the truth is "nobody clicked".
	//
	// The window is passed as an explicit half-open timestamptz range
	// [range_start, range_end) rather than derived from the date bounds in SQL. That
	// keeps the predicate sargable, so Postgres range-scans clicks_link_time_idx
	// instead of evaluating a date expression for every row in the table.
	GetClicksPerDay(ctx context.Context, arg GetClicksPerDayParams) ([]GetClicksPerDayRow, error)
	// The redirect hot path, on cache miss only.
	GetLinkByShortCode(ctx context.Context, shortCode string) (Link, error)
	// Ownership is part of the predicate, not a check after the fact: a link that
	// belongs to someone else is indistinguishable from one that does not exist,
	// so stats cannot be used to probe for other users' codes.
	GetLinkByShortCodeForUser(ctx context.Context, arg GetLinkByShortCodeForUserParams) (Link, error)
	// email is citext, so this is case-insensitive without lower() at the call site.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Runs in the same transaction as BulkInsertClicks, so a click row and its
	// counter increment commit or roll back together.
	//
	// Static SQL over two parallel arrays rather than a dynamically built VALUES
	// list: one prepared statement, one plan, no string building. Ordering the
	// update by id keeps concurrent worker transactions from deadlocking when their
	// batches touch the same links in different orders.
	IncrementClickCounts(ctx context.Context, arg IncrementClickCountsParams) error
	// Row-value comparison, not `created_at < x OR (created_at = x AND id < y)`.
	// Postgres can drive links_user_created_idx directly from a row constructor,
	// and it is correct when two links share a created_at to the microsecond.
	ListLinksAfter(ctx context.Context, arg ListLinksAfterParams) ([]Link, error)
	// Keyset pagination, page one. Separate from ListLinksAfter because sqlc emits
	// static SQL: a `WHERE ... OR @cursor IS NULL` predicate would collapse into a
	// filter that cannot use links_user_created_idx. Two honest queries beat one
	// query that quietly stops using its index.
	// Callers pass page_size = limit + 1 and use the extra row to detect "has more".
	ListLinksFirstPage(ctx context.Context, arg ListLinksFirstPageParams) ([]Link, error)
}

var _ Querier = (*Queries)(nil)
